# Generated by Django 3.0.6 on 2020-05-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
    ]
