# Generated by Django 3.0.6 on 2020-05-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20200518_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classTaken', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.UserProfile')),
            ],
        ),
    ]
