# Generated by Django 3.0.6 on 2020-05-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20200519_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtaken',
            name='classTaken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Class'),
        ),
    ]
