# Generated by Django 3.0.6 on 2020-05-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20200519_0958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classtaken',
            unique_together={('user', 'classTaken')},
        ),
    ]
